# Generated by Django 5.2.17 on 2026-09-28 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Plataforma')),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('genero', models.CharField(max_length=50, verbose_name='Género')),
                ('precio', models.PositiveIntegerField(verbose_name='Precio')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegosApp.plataforma', verbose_name='Plataforma')),
            ],
            options={
                'verbose_name': 'Juego',
                'verbose_name_plural': 'Juegos',
            },
        ),
    ]
